# Generated by Django 3.2.6 on 2021-08-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210806_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
